// Generated by jextract

package org.sherman.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$68 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$68() {}
    static final FunctionDescriptor io_uring_prep_rw_panama$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle io_uring_prep_rw_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_rw_panama",
        constants$68.io_uring_prep_rw_panama$FUNC
    );
    static final FunctionDescriptor io_uring_prep_splice_panama$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_splice_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_splice_panama",
        constants$68.io_uring_prep_splice_panama$FUNC
    );
    static final FunctionDescriptor io_uring_prep_tee_panama$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_tee_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_tee_panama",
        constants$68.io_uring_prep_tee_panama$FUNC
    );
    static final FunctionDescriptor io_uring_prep_readv_panama$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle io_uring_prep_readv_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_readv_panama",
        constants$68.io_uring_prep_readv_panama$FUNC
    );
    static final FunctionDescriptor io_uring_prep_readv2_panama$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_readv2_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_readv2_panama",
        constants$68.io_uring_prep_readv2_panama$FUNC
    );
    static final FunctionDescriptor io_uring_prep_read_fixed_panama$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_read_fixed_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_read_fixed_panama",
        constants$68.io_uring_prep_read_fixed_panama$FUNC
    );
}


