// Generated by jextract

package org.sherman.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$74 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$74() {}
    static final FunctionDescriptor io_uring_buf_ring_add_panama$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_buf_ring_add_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_buf_ring_add_panama",
        constants$74.io_uring_buf_ring_add_panama$FUNC
    );
    static final FunctionDescriptor io_uring_buf_ring_advance_panama$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_buf_ring_advance_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_buf_ring_advance_panama",
        constants$74.io_uring_buf_ring_advance_panama$FUNC
    );
    static final FunctionDescriptor io_uring_buf_ring_cq_advance_panama$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_buf_ring_cq_advance_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_buf_ring_cq_advance_panama",
        constants$74.io_uring_buf_ring_cq_advance_panama$FUNC
    );
    static final FunctionDescriptor io_uring_get_sqe$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_get_sqe$MH = RuntimeHelper.downcallHandle(
        "io_uring_get_sqe",
        constants$74.io_uring_get_sqe$FUNC
    );
    static final FunctionDescriptor io_uring_mlock_size$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_mlock_size$MH = RuntimeHelper.downcallHandle(
        "io_uring_mlock_size",
        constants$74.io_uring_mlock_size$FUNC
    );
    static final FunctionDescriptor io_uring_mlock_size_params$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_mlock_size_params$MH = RuntimeHelper.downcallHandle(
        "io_uring_mlock_size_params",
        constants$74.io_uring_mlock_size_params$FUNC
    );
}


