// Generated by jextract

package org.sherman.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$52 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$52() {}
    static final FunctionDescriptor fcntl64$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle fcntl64$MH = RuntimeHelper.downcallHandleVariadic(
        "fcntl64",
        constants$52.fcntl64$FUNC
    );
    static final FunctionDescriptor open$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle open$MH = RuntimeHelper.downcallHandleVariadic(
        "open",
        constants$52.open$FUNC
    );
    static final FunctionDescriptor open64$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle open64$MH = RuntimeHelper.downcallHandleVariadic(
        "open64",
        constants$52.open64$FUNC
    );
    static final FunctionDescriptor openat$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle openat$MH = RuntimeHelper.downcallHandleVariadic(
        "openat",
        constants$52.openat$FUNC
    );
    static final FunctionDescriptor openat64$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle openat64$MH = RuntimeHelper.downcallHandleVariadic(
        "openat64",
        constants$52.openat64$FUNC
    );
    static final FunctionDescriptor creat$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle creat$MH = RuntimeHelper.downcallHandle(
        "creat",
        constants$52.creat$FUNC
    );
}


