// Generated by jextract

package org.sherman.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$72 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$72() {}
    static final FunctionDescriptor io_uring_sqring_wait_panama$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_sqring_wait_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_sqring_wait_panama",
        constants$72.io_uring_sqring_wait_panama$FUNC
    );
    static final FunctionDescriptor io_uring_cq_ready_panama$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_cq_ready_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_cq_ready_panama",
        constants$72.io_uring_cq_ready_panama$FUNC
    );
    static final FunctionDescriptor io_uring_cq_has_overflow_panama$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_cq_has_overflow_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_cq_has_overflow_panama",
        constants$72.io_uring_cq_has_overflow_panama$FUNC
    );
    static final FunctionDescriptor io_uring_cq_eventfd_enabled_panama$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_cq_eventfd_enabled_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_cq_eventfd_enabled_panama",
        constants$72.io_uring_cq_eventfd_enabled_panama$FUNC
    );
    static final FunctionDescriptor io_uring_cq_eventfd_toggle_panama$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_BOOL$LAYOUT
    );
    static final MethodHandle io_uring_cq_eventfd_toggle_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_cq_eventfd_toggle_panama",
        constants$72.io_uring_cq_eventfd_toggle_panama$FUNC
    );
    static final FunctionDescriptor io_uring_wait_cqe_nr_panama$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_wait_cqe_nr_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_wait_cqe_nr_panama",
        constants$72.io_uring_wait_cqe_nr_panama$FUNC
    );
}


