// Generated by jextract

package org.sherman.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$63 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$63() {}
    static final FunctionDescriptor io_uring_register_probe$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_probe$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_probe",
        constants$63.io_uring_register_probe$FUNC
    );
    static final FunctionDescriptor io_uring_register_personality$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_register_personality$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_personality",
        constants$63.io_uring_register_personality$FUNC
    );
    static final FunctionDescriptor io_uring_unregister_personality$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_unregister_personality$MH = RuntimeHelper.downcallHandle(
        "io_uring_unregister_personality",
        constants$63.io_uring_unregister_personality$FUNC
    );
    static final FunctionDescriptor io_uring_register_restrictions$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_restrictions$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_restrictions",
        constants$63.io_uring_register_restrictions$FUNC
    );
    static final FunctionDescriptor io_uring_enable_rings$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_enable_rings$MH = RuntimeHelper.downcallHandle(
        "io_uring_enable_rings",
        constants$63.io_uring_enable_rings$FUNC
    );
    static final FunctionDescriptor __io_uring_sqring_wait$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __io_uring_sqring_wait$MH = RuntimeHelper.downcallHandle(
        "__io_uring_sqring_wait",
        constants$63.__io_uring_sqring_wait$FUNC
    );
}


