// Generated by jextract

package org.sherman.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$58 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$58() {}
    static final FunctionDescriptor atomic_flag_clear_explicit$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle atomic_flag_clear_explicit$MH = RuntimeHelper.downcallHandle(
        "atomic_flag_clear_explicit",
        constants$58.atomic_flag_clear_explicit$FUNC
    );
    static final FunctionDescriptor io_uring_get_probe_ring$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_get_probe_ring$MH = RuntimeHelper.downcallHandle(
        "io_uring_get_probe_ring",
        constants$58.io_uring_get_probe_ring$FUNC
    );
    static final FunctionDescriptor io_uring_get_probe$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle io_uring_get_probe$MH = RuntimeHelper.downcallHandle(
        "io_uring_get_probe",
        constants$58.io_uring_get_probe$FUNC
    );
    static final FunctionDescriptor io_uring_free_probe$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_free_probe$MH = RuntimeHelper.downcallHandle(
        "io_uring_free_probe",
        constants$58.io_uring_free_probe$FUNC
    );
    static final FunctionDescriptor io_uring_opcode_supported_panama$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_opcode_supported_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_opcode_supported_panama",
        constants$58.io_uring_opcode_supported_panama$FUNC
    );
    static final FunctionDescriptor io_uring_queue_init_params$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_queue_init_params$MH = RuntimeHelper.downcallHandle(
        "io_uring_queue_init_params",
        constants$58.io_uring_queue_init_params$FUNC
    );
}


