// Generated by jextract

package org.sherman.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$67 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$67() {}
    static final FunctionDescriptor io_uring_sqe_set_data_panama$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_sqe_set_data_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_sqe_set_data_panama",
        constants$67.io_uring_sqe_set_data_panama$FUNC
    );
    static final FunctionDescriptor io_uring_cqe_get_data_panama$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_cqe_get_data_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_cqe_get_data_panama",
        constants$67.io_uring_cqe_get_data_panama$FUNC
    );
    static final FunctionDescriptor io_uring_sqe_set_data64_panama$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle io_uring_sqe_set_data64_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_sqe_set_data64_panama",
        constants$67.io_uring_sqe_set_data64_panama$FUNC
    );
    static final FunctionDescriptor io_uring_cqe_get_data64_panama$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_cqe_get_data64_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_cqe_get_data64_panama",
        constants$67.io_uring_cqe_get_data64_panama$FUNC
    );
    static final FunctionDescriptor io_uring_sqe_set_flags_panama$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_sqe_set_flags_panama$MH = RuntimeHelper.downcallHandle(
        "io_uring_sqe_set_flags_panama",
        constants$67.io_uring_sqe_set_flags_panama$FUNC
    );
    static final FunctionDescriptor __io_uring_set_target_fixed_file_panama$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle __io_uring_set_target_fixed_file_panama$MH = RuntimeHelper.downcallHandle(
        "__io_uring_set_target_fixed_file_panama",
        constants$67.__io_uring_set_target_fixed_file_panama$FUNC
    );
}


