// Generated by jextract

package org.sherman.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$54 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$54() {}
    static final FunctionDescriptor clone$__fn_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle clone$__fn_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$54.clone$__fn_DOWN$FUNC
    );
    static final FunctionDescriptor clone$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle clone$MH = RuntimeHelper.downcallHandleVariadic(
        "clone",
        constants$54.clone$FUNC
    );
    static final FunctionDescriptor unshare$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle unshare$MH = RuntimeHelper.downcallHandle(
        "unshare",
        constants$54.unshare$FUNC
    );
    static final FunctionDescriptor sched_getcpu$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle sched_getcpu$MH = RuntimeHelper.downcallHandle(
        "sched_getcpu",
        constants$54.sched_getcpu$FUNC
    );
    static final FunctionDescriptor getcpu$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle getcpu$MH = RuntimeHelper.downcallHandle(
        "getcpu",
        constants$54.getcpu$FUNC
    );
    static final FunctionDescriptor setns$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle setns$MH = RuntimeHelper.downcallHandle(
        "setns",
        constants$54.setns$FUNC
    );
}


