// Generated by jextract

package org.sherman;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * union {
 *     struct sockaddr* __sockaddr__;
 *     struct sockaddr_at* __sockaddr_at__;
 *     struct sockaddr_ax25* __sockaddr_ax25__;
 *     struct sockaddr_dl* __sockaddr_dl__;
 *     struct sockaddr_eon* __sockaddr_eon__;
 *     struct sockaddr_in* __sockaddr_in__;
 *     struct sockaddr_in6* __sockaddr_in6__;
 *     struct sockaddr_inarp* __sockaddr_inarp__;
 *     struct sockaddr_ipx* __sockaddr_ipx__;
 *     struct sockaddr_iso* __sockaddr_iso__;
 *     struct sockaddr_ns* __sockaddr_ns__;
 *     struct sockaddr_un* __sockaddr_un__;
 *     struct sockaddr_x25* __sockaddr_x25__;
 * };
 * }
 */
public class __SOCKADDR_ARG {

    static final UnionLayout $union$LAYOUT = MemoryLayout.unionLayout(
        Constants$root.C_POINTER$LAYOUT.withName("__sockaddr__"),
        Constants$root.C_POINTER$LAYOUT.withName("__sockaddr_at__"),
        Constants$root.C_POINTER$LAYOUT.withName("__sockaddr_ax25__"),
        Constants$root.C_POINTER$LAYOUT.withName("__sockaddr_dl__"),
        Constants$root.C_POINTER$LAYOUT.withName("__sockaddr_eon__"),
        Constants$root.C_POINTER$LAYOUT.withName("__sockaddr_in__"),
        Constants$root.C_POINTER$LAYOUT.withName("__sockaddr_in6__"),
        Constants$root.C_POINTER$LAYOUT.withName("__sockaddr_inarp__"),
        Constants$root.C_POINTER$LAYOUT.withName("__sockaddr_ipx__"),
        Constants$root.C_POINTER$LAYOUT.withName("__sockaddr_iso__"),
        Constants$root.C_POINTER$LAYOUT.withName("__sockaddr_ns__"),
        Constants$root.C_POINTER$LAYOUT.withName("__sockaddr_un__"),
        Constants$root.C_POINTER$LAYOUT.withName("__sockaddr_x25__")
    );
    public static MemoryLayout $LAYOUT() {
        return __SOCKADDR_ARG.$union$LAYOUT;
    }
    static final VarHandle __sockaddr__$VH = $union$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__sockaddr__"));
    public static VarHandle __sockaddr__$VH() {
        return __SOCKADDR_ARG.__sockaddr__$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct sockaddr* __sockaddr__;
     * }
     */
    public static MemorySegment __sockaddr__$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr__$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct sockaddr* __sockaddr__;
     * }
     */
    public static void __sockaddr__$set(MemorySegment seg, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr__$VH.set(seg, x);
    }
    public static MemorySegment __sockaddr__$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr__$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __sockaddr__$set(MemorySegment seg, long index, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr__$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __sockaddr_at__$VH = $union$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__sockaddr_at__"));
    public static VarHandle __sockaddr_at__$VH() {
        return __SOCKADDR_ARG.__sockaddr_at__$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct sockaddr_at* __sockaddr_at__;
     * }
     */
    public static MemorySegment __sockaddr_at__$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_at__$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct sockaddr_at* __sockaddr_at__;
     * }
     */
    public static void __sockaddr_at__$set(MemorySegment seg, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_at__$VH.set(seg, x);
    }
    public static MemorySegment __sockaddr_at__$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_at__$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __sockaddr_at__$set(MemorySegment seg, long index, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_at__$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __sockaddr_ax25__$VH = $union$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__sockaddr_ax25__"));
    public static VarHandle __sockaddr_ax25__$VH() {
        return __SOCKADDR_ARG.__sockaddr_ax25__$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct sockaddr_ax25* __sockaddr_ax25__;
     * }
     */
    public static MemorySegment __sockaddr_ax25__$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_ax25__$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct sockaddr_ax25* __sockaddr_ax25__;
     * }
     */
    public static void __sockaddr_ax25__$set(MemorySegment seg, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_ax25__$VH.set(seg, x);
    }
    public static MemorySegment __sockaddr_ax25__$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_ax25__$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __sockaddr_ax25__$set(MemorySegment seg, long index, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_ax25__$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __sockaddr_dl__$VH = $union$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__sockaddr_dl__"));
    public static VarHandle __sockaddr_dl__$VH() {
        return __SOCKADDR_ARG.__sockaddr_dl__$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct sockaddr_dl* __sockaddr_dl__;
     * }
     */
    public static MemorySegment __sockaddr_dl__$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_dl__$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct sockaddr_dl* __sockaddr_dl__;
     * }
     */
    public static void __sockaddr_dl__$set(MemorySegment seg, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_dl__$VH.set(seg, x);
    }
    public static MemorySegment __sockaddr_dl__$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_dl__$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __sockaddr_dl__$set(MemorySegment seg, long index, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_dl__$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __sockaddr_eon__$VH = $union$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__sockaddr_eon__"));
    public static VarHandle __sockaddr_eon__$VH() {
        return __SOCKADDR_ARG.__sockaddr_eon__$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct sockaddr_eon* __sockaddr_eon__;
     * }
     */
    public static MemorySegment __sockaddr_eon__$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_eon__$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct sockaddr_eon* __sockaddr_eon__;
     * }
     */
    public static void __sockaddr_eon__$set(MemorySegment seg, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_eon__$VH.set(seg, x);
    }
    public static MemorySegment __sockaddr_eon__$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_eon__$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __sockaddr_eon__$set(MemorySegment seg, long index, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_eon__$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __sockaddr_in__$VH = $union$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__sockaddr_in__"));
    public static VarHandle __sockaddr_in__$VH() {
        return __SOCKADDR_ARG.__sockaddr_in__$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct sockaddr_in* __sockaddr_in__;
     * }
     */
    public static MemorySegment __sockaddr_in__$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_in__$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct sockaddr_in* __sockaddr_in__;
     * }
     */
    public static void __sockaddr_in__$set(MemorySegment seg, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_in__$VH.set(seg, x);
    }
    public static MemorySegment __sockaddr_in__$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_in__$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __sockaddr_in__$set(MemorySegment seg, long index, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_in__$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __sockaddr_in6__$VH = $union$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__sockaddr_in6__"));
    public static VarHandle __sockaddr_in6__$VH() {
        return __SOCKADDR_ARG.__sockaddr_in6__$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct sockaddr_in6* __sockaddr_in6__;
     * }
     */
    public static MemorySegment __sockaddr_in6__$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_in6__$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct sockaddr_in6* __sockaddr_in6__;
     * }
     */
    public static void __sockaddr_in6__$set(MemorySegment seg, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_in6__$VH.set(seg, x);
    }
    public static MemorySegment __sockaddr_in6__$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_in6__$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __sockaddr_in6__$set(MemorySegment seg, long index, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_in6__$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __sockaddr_inarp__$VH = $union$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__sockaddr_inarp__"));
    public static VarHandle __sockaddr_inarp__$VH() {
        return __SOCKADDR_ARG.__sockaddr_inarp__$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct sockaddr_inarp* __sockaddr_inarp__;
     * }
     */
    public static MemorySegment __sockaddr_inarp__$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_inarp__$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct sockaddr_inarp* __sockaddr_inarp__;
     * }
     */
    public static void __sockaddr_inarp__$set(MemorySegment seg, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_inarp__$VH.set(seg, x);
    }
    public static MemorySegment __sockaddr_inarp__$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_inarp__$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __sockaddr_inarp__$set(MemorySegment seg, long index, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_inarp__$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __sockaddr_ipx__$VH = $union$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__sockaddr_ipx__"));
    public static VarHandle __sockaddr_ipx__$VH() {
        return __SOCKADDR_ARG.__sockaddr_ipx__$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct sockaddr_ipx* __sockaddr_ipx__;
     * }
     */
    public static MemorySegment __sockaddr_ipx__$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_ipx__$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct sockaddr_ipx* __sockaddr_ipx__;
     * }
     */
    public static void __sockaddr_ipx__$set(MemorySegment seg, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_ipx__$VH.set(seg, x);
    }
    public static MemorySegment __sockaddr_ipx__$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_ipx__$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __sockaddr_ipx__$set(MemorySegment seg, long index, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_ipx__$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __sockaddr_iso__$VH = $union$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__sockaddr_iso__"));
    public static VarHandle __sockaddr_iso__$VH() {
        return __SOCKADDR_ARG.__sockaddr_iso__$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct sockaddr_iso* __sockaddr_iso__;
     * }
     */
    public static MemorySegment __sockaddr_iso__$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_iso__$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct sockaddr_iso* __sockaddr_iso__;
     * }
     */
    public static void __sockaddr_iso__$set(MemorySegment seg, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_iso__$VH.set(seg, x);
    }
    public static MemorySegment __sockaddr_iso__$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_iso__$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __sockaddr_iso__$set(MemorySegment seg, long index, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_iso__$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __sockaddr_ns__$VH = $union$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__sockaddr_ns__"));
    public static VarHandle __sockaddr_ns__$VH() {
        return __SOCKADDR_ARG.__sockaddr_ns__$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct sockaddr_ns* __sockaddr_ns__;
     * }
     */
    public static MemorySegment __sockaddr_ns__$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_ns__$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct sockaddr_ns* __sockaddr_ns__;
     * }
     */
    public static void __sockaddr_ns__$set(MemorySegment seg, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_ns__$VH.set(seg, x);
    }
    public static MemorySegment __sockaddr_ns__$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_ns__$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __sockaddr_ns__$set(MemorySegment seg, long index, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_ns__$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __sockaddr_un__$VH = $union$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__sockaddr_un__"));
    public static VarHandle __sockaddr_un__$VH() {
        return __SOCKADDR_ARG.__sockaddr_un__$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct sockaddr_un* __sockaddr_un__;
     * }
     */
    public static MemorySegment __sockaddr_un__$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_un__$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct sockaddr_un* __sockaddr_un__;
     * }
     */
    public static void __sockaddr_un__$set(MemorySegment seg, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_un__$VH.set(seg, x);
    }
    public static MemorySegment __sockaddr_un__$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_un__$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __sockaddr_un__$set(MemorySegment seg, long index, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_un__$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __sockaddr_x25__$VH = $union$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__sockaddr_x25__"));
    public static VarHandle __sockaddr_x25__$VH() {
        return __SOCKADDR_ARG.__sockaddr_x25__$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct sockaddr_x25* __sockaddr_x25__;
     * }
     */
    public static MemorySegment __sockaddr_x25__$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_x25__$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct sockaddr_x25* __sockaddr_x25__;
     * }
     */
    public static void __sockaddr_x25__$set(MemorySegment seg, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_x25__$VH.set(seg, x);
    }
    public static MemorySegment __sockaddr_x25__$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)__SOCKADDR_ARG.__sockaddr_x25__$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __sockaddr_x25__$set(MemorySegment seg, long index, MemorySegment x) {
        __SOCKADDR_ARG.__sockaddr_x25__$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


