// Generated by jextract

package org.sherman;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$55 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$55() {}
    static final FunctionDescriptor __sched_cpucount$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __sched_cpucount$MH = RuntimeHelper.downcallHandle(
        "__sched_cpucount",
        constants$55.__sched_cpucount$FUNC
    );
    static final FunctionDescriptor __sched_cpualloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle __sched_cpualloc$MH = RuntimeHelper.downcallHandle(
        "__sched_cpualloc",
        constants$55.__sched_cpualloc$FUNC
    );
    static final FunctionDescriptor __sched_cpufree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __sched_cpufree$MH = RuntimeHelper.downcallHandle(
        "__sched_cpufree",
        constants$55.__sched_cpufree$FUNC
    );
    static final FunctionDescriptor sched_setparam$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sched_setparam$MH = RuntimeHelper.downcallHandle(
        "sched_setparam",
        constants$55.sched_setparam$FUNC
    );
    static final FunctionDescriptor sched_getparam$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sched_getparam$MH = RuntimeHelper.downcallHandle(
        "sched_getparam",
        constants$55.sched_getparam$FUNC
    );
    static final FunctionDescriptor sched_setscheduler$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sched_setscheduler$MH = RuntimeHelper.downcallHandle(
        "sched_setscheduler",
        constants$55.sched_setscheduler$FUNC
    );
}


