// Generated by jextract

package org.sherman;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$62 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$62() {}
    static final FunctionDescriptor io_uring_unregister_files$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_unregister_files$MH = RuntimeHelper.downcallHandle(
        "io_uring_unregister_files",
        constants$62.io_uring_unregister_files$FUNC
    );
    static final FunctionDescriptor io_uring_register_files_update$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_files_update$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_files_update",
        constants$62.io_uring_register_files_update$FUNC
    );
    static final FunctionDescriptor io_uring_register_eventfd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_eventfd$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_eventfd",
        constants$62.io_uring_register_eventfd$FUNC
    );
    static final FunctionDescriptor io_uring_register_eventfd_async$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_eventfd_async$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_eventfd_async",
        constants$62.io_uring_register_eventfd_async$FUNC
    );
    static final FunctionDescriptor io_uring_unregister_eventfd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_unregister_eventfd$MH = RuntimeHelper.downcallHandle(
        "io_uring_unregister_eventfd",
        constants$62.io_uring_unregister_eventfd$FUNC
    );
    static final FunctionDescriptor io_uring_register_probe$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_probe$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_probe",
        constants$62.io_uring_register_probe$FUNC
    );
}


