// Generated by jextract

package org.sherman;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final FunctionDescriptor lchmod$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle lchmod$MH = RuntimeHelper.downcallHandle(
        "lchmod",
        constants$6.lchmod$FUNC
    );
    static final FunctionDescriptor fchmod$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle fchmod$MH = RuntimeHelper.downcallHandle(
        "fchmod",
        constants$6.fchmod$FUNC
    );
    static final FunctionDescriptor fchmodat$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle fchmodat$MH = RuntimeHelper.downcallHandle(
        "fchmodat",
        constants$6.fchmodat$FUNC
    );
    static final FunctionDescriptor umask$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle umask$MH = RuntimeHelper.downcallHandle(
        "umask",
        constants$6.umask$FUNC
    );
    static final FunctionDescriptor getumask$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle getumask$MH = RuntimeHelper.downcallHandle(
        "getumask",
        constants$6.getumask$FUNC
    );
    static final FunctionDescriptor mkdir$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mkdir$MH = RuntimeHelper.downcallHandle(
        "mkdir",
        constants$6.mkdir$FUNC
    );
}


