// Generated by jextract

package org.sherman;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct f_owner_ex {
 *     enum __pid_type type;
 *     __pid_t pid;
 * };
 * }
 */
public class f_owner_ex {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("type"),
        Constants$root.C_INT$LAYOUT.withName("pid")
    ).withName("f_owner_ex");
    public static MemoryLayout $LAYOUT() {
        return f_owner_ex.$struct$LAYOUT;
    }
    static final VarHandle type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("type"));
    public static VarHandle type$VH() {
        return f_owner_ex.type$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enum __pid_type type;
     * }
     */
    public static int type$get(MemorySegment seg) {
        return (int)f_owner_ex.type$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enum __pid_type type;
     * }
     */
    public static void type$set(MemorySegment seg, int x) {
        f_owner_ex.type$VH.set(seg, x);
    }
    public static int type$get(MemorySegment seg, long index) {
        return (int)f_owner_ex.type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, int x) {
        f_owner_ex.type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle pid$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("pid"));
    public static VarHandle pid$VH() {
        return f_owner_ex.pid$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __pid_t pid;
     * }
     */
    public static int pid$get(MemorySegment seg) {
        return (int)f_owner_ex.pid$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __pid_t pid;
     * }
     */
    public static void pid$set(MemorySegment seg, int x) {
        f_owner_ex.pid$VH.set(seg, x);
    }
    public static int pid$get(MemorySegment seg, long index) {
        return (int)f_owner_ex.pid$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void pid$set(MemorySegment seg, long index, int x) {
        f_owner_ex.pid$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


