// Generated by jextract

package org.sherman;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct file_dedupe_range {
 *     __u64 src_offset;
 *     __u64 src_length;
 *     __u16 dest_count;
 *     __u16 reserved1;
 *     __u32 reserved2;
 *     struct file_dedupe_range_info info[0];
 * };
 * }
 */
public class file_dedupe_range {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("src_offset"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("src_length"),
        Constants$root.C_SHORT$LAYOUT.withName("dest_count"),
        Constants$root.C_SHORT$LAYOUT.withName("reserved1"),
        Constants$root.C_INT$LAYOUT.withName("reserved2"),
        MemoryLayout.sequenceLayout(0, MemoryLayout.structLayout(
            Constants$root.C_LONG_LONG$LAYOUT.withName("dest_fd"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("dest_offset"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("bytes_deduped"),
            Constants$root.C_INT$LAYOUT.withName("status"),
            Constants$root.C_INT$LAYOUT.withName("reserved")
        ).withName("file_dedupe_range_info")).withName("info")
    ).withName("file_dedupe_range");
    public static MemoryLayout $LAYOUT() {
        return file_dedupe_range.$struct$LAYOUT;
    }
    static final VarHandle src_offset$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("src_offset"));
    public static VarHandle src_offset$VH() {
        return file_dedupe_range.src_offset$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __u64 src_offset;
     * }
     */
    public static long src_offset$get(MemorySegment seg) {
        return (long)file_dedupe_range.src_offset$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __u64 src_offset;
     * }
     */
    public static void src_offset$set(MemorySegment seg, long x) {
        file_dedupe_range.src_offset$VH.set(seg, x);
    }
    public static long src_offset$get(MemorySegment seg, long index) {
        return (long)file_dedupe_range.src_offset$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void src_offset$set(MemorySegment seg, long index, long x) {
        file_dedupe_range.src_offset$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle src_length$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("src_length"));
    public static VarHandle src_length$VH() {
        return file_dedupe_range.src_length$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __u64 src_length;
     * }
     */
    public static long src_length$get(MemorySegment seg) {
        return (long)file_dedupe_range.src_length$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __u64 src_length;
     * }
     */
    public static void src_length$set(MemorySegment seg, long x) {
        file_dedupe_range.src_length$VH.set(seg, x);
    }
    public static long src_length$get(MemorySegment seg, long index) {
        return (long)file_dedupe_range.src_length$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void src_length$set(MemorySegment seg, long index, long x) {
        file_dedupe_range.src_length$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle dest_count$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("dest_count"));
    public static VarHandle dest_count$VH() {
        return file_dedupe_range.dest_count$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __u16 dest_count;
     * }
     */
    public static short dest_count$get(MemorySegment seg) {
        return (short)file_dedupe_range.dest_count$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __u16 dest_count;
     * }
     */
    public static void dest_count$set(MemorySegment seg, short x) {
        file_dedupe_range.dest_count$VH.set(seg, x);
    }
    public static short dest_count$get(MemorySegment seg, long index) {
        return (short)file_dedupe_range.dest_count$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void dest_count$set(MemorySegment seg, long index, short x) {
        file_dedupe_range.dest_count$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle reserved1$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("reserved1"));
    public static VarHandle reserved1$VH() {
        return file_dedupe_range.reserved1$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __u16 reserved1;
     * }
     */
    public static short reserved1$get(MemorySegment seg) {
        return (short)file_dedupe_range.reserved1$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __u16 reserved1;
     * }
     */
    public static void reserved1$set(MemorySegment seg, short x) {
        file_dedupe_range.reserved1$VH.set(seg, x);
    }
    public static short reserved1$get(MemorySegment seg, long index) {
        return (short)file_dedupe_range.reserved1$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void reserved1$set(MemorySegment seg, long index, short x) {
        file_dedupe_range.reserved1$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle reserved2$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("reserved2"));
    public static VarHandle reserved2$VH() {
        return file_dedupe_range.reserved2$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __u32 reserved2;
     * }
     */
    public static int reserved2$get(MemorySegment seg) {
        return (int)file_dedupe_range.reserved2$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __u32 reserved2;
     * }
     */
    public static void reserved2$set(MemorySegment seg, int x) {
        file_dedupe_range.reserved2$VH.set(seg, x);
    }
    public static int reserved2$get(MemorySegment seg, long index) {
        return (int)file_dedupe_range.reserved2$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void reserved2$set(MemorySegment seg, long index, int x) {
        file_dedupe_range.reserved2$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


