// Generated by jextract

package org.sherman;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct io_uring_sync_cancel_reg {
 *     __u64 addr;
 *     __s32 fd;
 *     __u32 flags;
 *     struct __kernel_timespec timeout;
 *     __u64 pad[4];
 * };
 * }
 */
public class io_uring_sync_cancel_reg {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("addr"),
        Constants$root.C_INT$LAYOUT.withName("fd"),
        Constants$root.C_INT$LAYOUT.withName("flags"),
        MemoryLayout.structLayout(
            Constants$root.C_LONG_LONG$LAYOUT.withName("tv_sec"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("tv_nsec")
        ).withName("timeout"),
        MemoryLayout.sequenceLayout(4, Constants$root.C_LONG_LONG$LAYOUT).withName("pad")
    ).withName("io_uring_sync_cancel_reg");
    public static MemoryLayout $LAYOUT() {
        return io_uring_sync_cancel_reg.$struct$LAYOUT;
    }
    static final VarHandle addr$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("addr"));
    public static VarHandle addr$VH() {
        return io_uring_sync_cancel_reg.addr$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __u64 addr;
     * }
     */
    public static long addr$get(MemorySegment seg) {
        return (long)io_uring_sync_cancel_reg.addr$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __u64 addr;
     * }
     */
    public static void addr$set(MemorySegment seg, long x) {
        io_uring_sync_cancel_reg.addr$VH.set(seg, x);
    }
    public static long addr$get(MemorySegment seg, long index) {
        return (long)io_uring_sync_cancel_reg.addr$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void addr$set(MemorySegment seg, long index, long x) {
        io_uring_sync_cancel_reg.addr$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle fd$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fd"));
    public static VarHandle fd$VH() {
        return io_uring_sync_cancel_reg.fd$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __s32 fd;
     * }
     */
    public static int fd$get(MemorySegment seg) {
        return (int)io_uring_sync_cancel_reg.fd$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __s32 fd;
     * }
     */
    public static void fd$set(MemorySegment seg, int x) {
        io_uring_sync_cancel_reg.fd$VH.set(seg, x);
    }
    public static int fd$get(MemorySegment seg, long index) {
        return (int)io_uring_sync_cancel_reg.fd$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fd$set(MemorySegment seg, long index, int x) {
        io_uring_sync_cancel_reg.fd$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle flags$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("flags"));
    public static VarHandle flags$VH() {
        return io_uring_sync_cancel_reg.flags$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __u32 flags;
     * }
     */
    public static int flags$get(MemorySegment seg) {
        return (int)io_uring_sync_cancel_reg.flags$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __u32 flags;
     * }
     */
    public static void flags$set(MemorySegment seg, int x) {
        io_uring_sync_cancel_reg.flags$VH.set(seg, x);
    }
    public static int flags$get(MemorySegment seg, long index) {
        return (int)io_uring_sync_cancel_reg.flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void flags$set(MemorySegment seg, long index, int x) {
        io_uring_sync_cancel_reg.flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment timeout$slice(MemorySegment seg) {
        return seg.asSlice(16, 16);
    }
    public static MemorySegment pad$slice(MemorySegment seg) {
        return seg.asSlice(32, 32);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


