// Generated by jextract

package org.sherman;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct io_uring_notification_slot {
 *     __u64 tag;
 *     __u64 resv[3];
 * };
 * }
 */
public class io_uring_notification_slot {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("tag"),
        MemoryLayout.sequenceLayout(3, Constants$root.C_LONG_LONG$LAYOUT).withName("resv")
    ).withName("io_uring_notification_slot");
    public static MemoryLayout $LAYOUT() {
        return io_uring_notification_slot.$struct$LAYOUT;
    }
    static final VarHandle tag$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("tag"));
    public static VarHandle tag$VH() {
        return io_uring_notification_slot.tag$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __u64 tag;
     * }
     */
    public static long tag$get(MemorySegment seg) {
        return (long)io_uring_notification_slot.tag$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __u64 tag;
     * }
     */
    public static void tag$set(MemorySegment seg, long x) {
        io_uring_notification_slot.tag$VH.set(seg, x);
    }
    public static long tag$get(MemorySegment seg, long index) {
        return (long)io_uring_notification_slot.tag$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void tag$set(MemorySegment seg, long index, long x) {
        io_uring_notification_slot.tag$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment resv$slice(MemorySegment seg) {
        return seg.asSlice(8, 24);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


