// Generated by jextract

package org.sherman;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct io_uring_cqe {
 *     __u64 user_data;
 *     __s32 res;
 *     __u32 flags;
 *     __u64 big_cqe[];
 * };
 * }
 */
public class io_uring_cqe {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("user_data"),
        Constants$root.C_INT$LAYOUT.withName("res"),
        Constants$root.C_INT$LAYOUT.withName("flags"),
        MemoryLayout.sequenceLayout(0, Constants$root.C_LONG_LONG$LAYOUT).withName("big_cqe")
    ).withName("io_uring_cqe");
    public static MemoryLayout $LAYOUT() {
        return io_uring_cqe.$struct$LAYOUT;
    }
    static final VarHandle user_data$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("user_data"));
    public static VarHandle user_data$VH() {
        return io_uring_cqe.user_data$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __u64 user_data;
     * }
     */
    public static long user_data$get(MemorySegment seg) {
        return (long)io_uring_cqe.user_data$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __u64 user_data;
     * }
     */
    public static void user_data$set(MemorySegment seg, long x) {
        io_uring_cqe.user_data$VH.set(seg, x);
    }
    public static long user_data$get(MemorySegment seg, long index) {
        return (long)io_uring_cqe.user_data$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void user_data$set(MemorySegment seg, long index, long x) {
        io_uring_cqe.user_data$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle res$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("res"));
    public static VarHandle res$VH() {
        return io_uring_cqe.res$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __s32 res;
     * }
     */
    public static int res$get(MemorySegment seg) {
        return (int)io_uring_cqe.res$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __s32 res;
     * }
     */
    public static void res$set(MemorySegment seg, int x) {
        io_uring_cqe.res$VH.set(seg, x);
    }
    public static int res$get(MemorySegment seg, long index) {
        return (int)io_uring_cqe.res$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void res$set(MemorySegment seg, long index, int x) {
        io_uring_cqe.res$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle flags$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("flags"));
    public static VarHandle flags$VH() {
        return io_uring_cqe.flags$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * __u32 flags;
     * }
     */
    public static int flags$get(MemorySegment seg) {
        return (int)io_uring_cqe.flags$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * __u32 flags;
     * }
     */
    public static void flags$set(MemorySegment seg, int x) {
        io_uring_cqe.flags$VH.set(seg, x);
    }
    public static int flags$get(MemorySegment seg, long index) {
        return (int)io_uring_cqe.flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void flags$set(MemorySegment seg, long index, int x) {
        io_uring_cqe.flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


